"""Add owner columnsфыфы

Revision ID: 8c58de911cba
Revises: fcee016b3fd2
Create Date: 2022-04-04 17:17:11.806510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c58de911cba'
down_revision = 'fcee016b3fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
